on: [push]

name: Continuous Integration

jobs:
  check:
    name: Check if code compiles
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-13, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install dependencies for the project (Windows)
        if: matrix.os == 'windows-latest'
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install winflexbison3 meson
          
      - name: Install dependencies for the project (macOS, Linux)
        if: matrix.os != 'windows-latest'
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt update && sudo apt install meson bison flex cmake libfl-dev clang
            echo "CXX=clang++" >> $GITHUB_ENV
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew install meson bison flex llvm
            echo "CXX=$(brew --prefix llvm)/bin/clang++" >> $GITHUB_ENV
            echo "$(brew --prefix bison)/bin" >> $GITHUB_PATH
            echo "$(brew --prefix flex)/bin" >> $GITHUB_PATH
            echo "LDFLAGS=-L$(brew --prefix flex)/lib" >> $GITHUB_ENV
            echo "CPPFLAGS=-I$(brew --prefix flex)/include" >> $GITHUB_ENV
          fi

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install subprojects
        run: meson wrap install catch2

      - name: Setup build directory
        run: meson setup build

      - name: Run all tests
        run: meson test -C build
