on: [push]

name: Continuous Integration (UNIX-based)

jobs:
  check:
    name: Check if code compiles
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-13]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install dependencies for the project (macOS, Linux)
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt update && sudo apt install meson bison flex clang
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew install meson bison flex
            echo "/opt/homebrew/opt/bison/bin" >> $GITHUB_PATH
            echo "/opt/homebrew/opt/flex/bin" >> $GITHUB_PATH
          fi

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup build directory
        run: meson setup build

      - name: Run all tests
        run: meson test -C build
