on: [push]

name: Continuous Integration

jobs:
  check:
    name: Check if code compiles
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-13]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install dependencies for the project (macOS, Linux)
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt update && sudo apt install meson bison flex cmake libfl-dev clang
            echo "CXX=clang++" >> $GITHUB_ENV
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew install meson bison flex gcc
            echo "$(brew --prefix bison)/bin" >> $GITHUB_PATH
            echo "$(brew --prefix flex)/bin" >> $GITHUB_PATH
          fi

      - name: Use newer version of clang on Intel-based macos
        if: matrix.os == 'macos-13'
        run: |
          echo "CXX=$(brew --prefix llvm)/bin/g++" >> $GITHUB_ENV

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install subprojects
        run: meson wrap install catch2

      - name: Setup build directory
        run: meson setup build

      - name: Run all tests
        run: meson test -C build
