on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  check:
    name: Verify code behaves as intended
    runs-on: ${{ inputs.os }}

    steps:
      - name: Install dependencies for the project (macOS, Linux)
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt update && sudo apt install meson bison flex cmake libfl-dev clang
            echo "CXX=clang++" >> $GITHUB_ENV
            echo "LDFLAGS=-static-libstdc++" >> $GITHUB_ENV
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew install meson bison flex llvm
            echo "CXX=$(brew --prefix llvm)/bin/clang++" >> $GITHUB_ENV
            # on macOS, bison and flex are already provided, but we want
            # to use the newer versions provided by Homebrew, so we have
            # to append them into the path via GitHub's GITHUB_PATH variable.
            echo "$(brew --prefix bison)/bin" >> $GITHUB_PATH
            echo "$(brew --prefix flex)/bin" >> $GITHUB_PATH
            # Likewise, we want to use the latest header files for flex.
            echo "LDFLAGS=-L$(brew --prefix flex)/lib" >> $GITHUB_ENV
            echo "CPPFLAGS=-I$(brew --prefix flex)/include" >> $GITHUB_ENV
          fi

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install subprojects
        run: meson wrap install catch2

      - name: Setup build directory
        run: meson setup build
