on: [push]

name: Continuous Integration (Windows)

jobs:
  check:
    name: Check if code compiles

    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Install dependencies for the project (Windows)
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-clang
            mingw-w64-x86_64-python
            meson
            bison
            flex
            cmake

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install subprojects
        run: meson wrap install catch2

      - name: Setup build directory
        run: meson setup build

      - name: Run all tests
        run: meson test -C build
