on: [push]

name: Continuous Integration (Windows)

jobs:
  check:
    name: Check if code compiles
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Install dependencies for the project (Windows)
        uses: msys2/setup-msys2@v2
        with:
          path-type: inherit
          update: true
          install: >-
            bison
            flex
            mingw-w64-x86_64-python
            mingw-w64-x86_64-meson
            mingw-w64-x86_64-openssl
            mingw-w64-x86_64-ca-certificates
            mingw-w64-x86_64-clang
            openssl
            ca-certificates
            meson
            git

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install subprojects
        run: |
          echo "LDFLAGS=-L/usr/lib" >> $GITHUB_ENV
          echo "CPPFLAGS=-I/usr/include" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV
          meson wrap install catch2

      - name: Setup build directory
        run: |
          meson setup build

      - name: Run all tests
        run: |
          meson test -C build
