on: [push]

name: Continuous Integration (Windows)

jobs:
  check:
    name: Check if code compiles
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          architecture: "x64"

      - name: Install dependencies for the project (Windows)
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            bison
            flex
            python
            meson

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install subprojects
        run: |
          meson wrap install catch2

      - name: Setup build directory
        run: |
          meson setup build

      - name: Run all tests
        run: |
          meson test -C build
